### ISSUE TITLE
Morpho Library issue

### ISSUE THREAD

**Issue by KeviChiu** [AntonelloDN/Morpho#20] opened 2023-11-26 21:24 UTC
Hi Antonelllo,

I am learning how to built up ENVI-MET model for the stimulation by following the your guideline. However, I the step of assigning material with Morpho library, it show the error " 1. Solution exception:The '¤' character, hexadecimal value 0xA4, cannot be included in a name. Line 798, position 17." I double check the field path, there is no such character occur.  Is there any solution for that? 
![Morpho Error](https://github.com/AntonelloDN/Morpho/assets/139073471/63d0ef5c-9cc0-4f6f-9a75-b5685a40dee1)

Thanks,
Kevin.C

**Comment by AntonelloDN** [comment] 2023-11-26 23:04
Hi @KeviChiu, I have been fixing this kind of error in this [discussion](https://github.com/AntonelloDN/Morpho/discussions/19). We can continue the discussion there. Can you write the version of envimet/Morpho installer and tell me if you have added user materials to Envimet?

**Comment by 433433433** [comment] 2023-12-15 15:28
1. Solution exception:The '¤' character, hexadecimal value 0xA4, cannot be included in a name. Line 407, position 17.
![微信图片_20231215232706] @AntonelloDN What is the cause of this problem? Do you have a specific installation tutorial

**Comment by AntonelloDN** [comment] 2023-12-15 15:47
> 1. Solution exception:The '¤' character, hexadecimal value 0xA4, cannot be included in a name. Line 407, position 17.
>    ![微信图片_20231215232706] @AntonelloDN What is the cause of this problem? Do you have a specific installation tutorial

Have you tested this [installer](https://github.com/AntonelloDN/Morpho/releases/tag/v1.10.0)?

**Comment by 433433433** [comment] 2023-12-15 16:00
I have tried the new plug-in and there is no problem with the original one, but the battery of Open Envimet Spaces is running incorrectly, showing 1. Solution exception:WindowsError. I don't know if it is the problem of the ENVIMET version. My version of ENVIMET is ENVI-met Headquarter  5.1.1
 ![29d5430cfcf2f223e9d4b221bebc792](https://github.com/AntonelloDN/Morpho/assets/153931712/54f00ad1-9fd3-4147-961a-087233a9cd12)
![29d5430cfcf2f223e9d4b221bebc792](https://github.com/AntonelloDN/Morpho/assets/153931712/f1ae6219-46bf-4dd6-873c-93a9b46d21c4)
@AntonelloDN

**Comment by AntonelloDN** [comment] 2023-12-26 14:26
Hi @433433433, `WindowsError` can be if the process doesn't have permission to access the file. 
The component that fails is a python script only - `os.startfile(_file_path)`
I close this issue because the library issue is solved. If you want you can open another issue for this error or a [Discussion](https://github.com/AntonelloDN/Morpho/discussions)

**Closed** 2023-12-26 14:27 UTC

**Comment by 433433433** [comment] 2024-01-05 17:33
@AntonelloDN  Thank you for your reply. Could you please tell me which version of LADYBUG and openstudio is compatible with MORPHOv1.10.0. Please reply as soon as possible, thanks again~

**Comment by AntonelloDN** [comment] 2024-01-05 20:40
Hi @433433433, you can combine Morpho with components of the new version of [LadybugTools](https://www.food4rhino.com/en/app/ladybug-tools).
I use Ladybug Tools to generate heatmaps. See this [example](https://github.com/AntonelloDN/Morpho/tree/master/deploy/examples/grasshopper/05_reading_results)

**Comment by 433433433** [comment] 2024-01-06 07:18
Thank you very much for your reply. I saw that you used ladybug v1.0.0 in the HEATMAP of example, but I did not find this older version of the installation package on food4rhino. Since I want to simulate building energy consumption, can other versions of laybugtool be compatible with Morpho1.10.0? @AntonelloDN

**Comment by 433433433** [comment] 2024-01-06 07:28
AND I used rhino7.4.2, when I tried to install ladybug1.0.9, the battery appeared yellow as shown in the picture, is the version not compatible?
![Uploading 微信图片_20240106152811.png…]()
